name: deploy-pages
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: master - Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: cloning repo 🛎
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        shell: bash
        run: npm install

      - name: Build
        shell: bash
        run: npm run build

      - name: deploy to github pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
